// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleTender.API.Entity.Context;

#nullable disable

namespace VehicleTender.API.Entity.Migrations
{
    [DbContext(typeof(VehicleTenderContext))]
    [Migration("20221002022954_bugfix")]
    partial class bugfix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.AdvertInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CarDetailInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Ceiling")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineBonnet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FrontBumper")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LeftFrontDoor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LeftFrontMudguard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LeftRearDoor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LeftRearMudguard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RearBonnet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RearBumper")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RightFrontDoor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RightFrontMudguard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RightRearDoor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RightRearMudguard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalTramerPrice")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AdvertInfo");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Authority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthorityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authority");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.BuyingTenderVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsItSold")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Offer")
                        .HasColumnType("money");

                    b.Property<int?>("TenderVehicleSalesId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenderVehicleSalesId");

                    b.HasIndex("UserId");

                    b.ToTable("BuyingTenderVehicle");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BodyType")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Brand")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<string>("TransmissionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.CarDetailInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AdvertInfoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CarDetailInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("CarId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CommissionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NotaryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdvertInfoId");

                    b.HasIndex("CarDetailInfoId");

                    b.HasIndex("CarId");

                    b.HasIndex("CommissionId");

                    b.HasIndex("NotaryId");

                    b.HasIndex("UserId");

                    b.ToTable("CarDetailInfo");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CarDetailInfoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CommissionPrice")
                        .HasColumnType("money");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Commission");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.CorporateDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("EnumCompanyTypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("EnumPacketId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnumCompanyTypeId");

                    b.HasIndex("EnumPacketId");

                    b.HasIndex("UserId");

                    b.ToTable("CorporateDetail");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.EnumCompanyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Type")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("EnumCompanyType");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.EnumPacket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("EnumPacket");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.EnumStatuType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EnumStatuType");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Expertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Expertise");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AdvertInfoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdvertInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.FavoriteFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FavoriteSearchCriteriaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("HardwareId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteSearchCriteriaId");

                    b.HasIndex("HardwareId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteFeature");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.FavoriteSearchCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("FavoriteSearchCriteria");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Hardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CarId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HardwareName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Hardware");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.IndividualVehiclePurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IndividualVehicleSalesId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserIdBuyer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndividualVehicleSalesId");

                    b.HasIndex("UserIdBuyer");

                    b.ToTable("IndividualVehiclePurchase");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.IndividualVehicleSales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CarDetailInfoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OfficialOffer")
                        .HasColumnType("money");

                    b.Property<decimal?>("TenEvaluationPrice")
                        .HasColumnType("money");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarDetailInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("IndividualVehicleSales");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LogProcessId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Page")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogProcessId");

                    b.HasIndex("UserId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.LogProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LogDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogProcess");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UserMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserMessage");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Notary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NotaryPrice")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Notary");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.PacketAuthority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnumPacketId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MonthlyTenderLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnumPacketId");

                    b.ToTable("PacketAuthority");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AdvertInfoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertInfoId");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.PurchasedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BuyerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CarDetailInfoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SellerUserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool?>("isItTender")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarDetailInfoId");

                    b.HasIndex("SellerUserId");

                    b.ToTable("PurchasedVehicle");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.RoleAuthority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AuthorityId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleAuthority");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.RoleUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Statu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("EnumStatuTypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("EnumStatuTypeId");

                    b.ToTable("Statu");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CarDetailInfoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarDetailInfoId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.TenderVehicleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CarDetailInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TenderVehicleSalesId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarDetailInfoId");

                    b.HasIndex("TenderVehicleSalesId");

                    b.ToTable("TenderVehicleDetail");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.TenderVehicleSales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AdvertInfoId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FavoriteCount")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatuId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("money");

                    b.Property<string>("TenderDuration")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenderEndDate")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TenderEndHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TenderMinumumPrice")
                        .HasColumnType("money");

                    b.Property<string>("TenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TenderStartingPrice")
                        .HasColumnType("money");

                    b.Property<bool?>("isItCorporate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AdvertInfoId");

                    b.HasIndex("StatuId");

                    b.ToTable("TenderVehicleSales");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.VehicleStatuHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CarDetailInfoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatuId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarDetailInfoId");

                    b.HasIndex("StatuId");

                    b.ToTable("VehicleStatuHistory");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.BuyingTenderVehicle", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.TenderVehicleSales", "TenderVehicleSales")
                        .WithMany("BuyingTenderVehicle")
                        .HasForeignKey("TenderVehicleSalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany("BuyingTenderVehicle")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderVehicleSales");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.CarDetailInfo", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.AdvertInfo", "AdvertInfo")
                        .WithMany()
                        .HasForeignKey("AdvertInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.AdvertInfo", null)
                        .WithMany("CarDetailInfo")
                        .HasForeignKey("CarDetailInfoId");

                    b.HasOne("VehicleTender.API.Entity.Entities.Commission", null)
                        .WithMany("CarDetailInfo")
                        .HasForeignKey("CarDetailInfoId");

                    b.HasOne("VehicleTender.API.Entity.Entities.Car", "Car")
                        .WithMany("CarDetailInfo")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.Commission", "Commission")
                        .WithMany()
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.Notary", "Notary")
                        .WithMany("CarDetailInfo")
                        .HasForeignKey("NotaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany("CarDetailInfo")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvertInfo");

                    b.Navigation("Car");

                    b.Navigation("Commission");

                    b.Navigation("Notary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.CorporateDetail", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.EnumCompanyType", "EnumCompanyType")
                        .WithMany("CorporateDetail")
                        .HasForeignKey("EnumCompanyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.EnumPacket", "EnumPacket")
                        .WithMany("CorporateDetail")
                        .HasForeignKey("EnumPacketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany("CorporateDetail")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnumCompanyType");

                    b.Navigation("EnumPacket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Favorite", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.AdvertInfo", "AdvertInfo")
                        .WithMany("Favorite")
                        .HasForeignKey("AdvertInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany("Favorite")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvertInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.FavoriteFeature", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.FavoriteSearchCriteria", "FavoriteSearchCriteria")
                        .WithMany()
                        .HasForeignKey("FavoriteSearchCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavoriteSearchCriteria");

                    b.Navigation("Hardware");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Hardware", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.IndividualVehiclePurchase", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.IndividualVehicleSales", "IndividualVehicleSales")
                        .WithMany("IndividualVehiclePurchase")
                        .HasForeignKey("IndividualVehicleSalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany("IndividualVehiclePurchase")
                        .HasForeignKey("UserIdBuyer");

                    b.Navigation("IndividualVehicleSales");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.IndividualVehicleSales", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.CarDetailInfo", "CarDetailInfo")
                        .WithMany("IndividualVehicleSales")
                        .HasForeignKey("CarDetailInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany("IndividualVehicleSales")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarDetailInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Log", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.LogProcess", "LogProcess")
                        .WithMany("Log")
                        .HasForeignKey("LogProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany("Log")
                        .HasForeignKey("UserId");

                    b.Navigation("LogProcess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Message", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany("Message")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.PacketAuthority", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.EnumPacket", "EnumPacket")
                        .WithMany("PacketAuthority")
                        .HasForeignKey("EnumPacketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnumPacket");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Picture", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.AdvertInfo", "AdvertInfo")
                        .WithMany("Picture")
                        .HasForeignKey("AdvertInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvertInfo");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.PurchasedVehicle", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.CarDetailInfo", "CarDetailInfo")
                        .WithMany("PurchasedVehicle")
                        .HasForeignKey("CarDetailInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "SellerUser")
                        .WithMany()
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarDetailInfo");

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.RoleAuthority", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.Authority", "Authority")
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.Role", "Role")
                        .WithMany("RoleAuthority")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.RoleUser", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.Role", "Role")
                        .WithMany("RoleUser")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany("RoleUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Statu", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.EnumStatuType", "EnumStatuType")
                        .WithMany("Statu")
                        .HasForeignKey("EnumStatuTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnumStatuType");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Stock", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.CarDetailInfo", "CarDetailInfo")
                        .WithMany("Stock")
                        .HasForeignKey("CarDetailInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.User", "User")
                        .WithMany("Stock")
                        .HasForeignKey("CustomerId");

                    b.Navigation("CarDetailInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.TenderVehicleDetail", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.CarDetailInfo", "CarDetailInfo")
                        .WithMany("TenderVehicleDetail")
                        .HasForeignKey("CarDetailInfoId");

                    b.HasOne("VehicleTender.API.Entity.Entities.TenderVehicleSales", "TenderVehicleSales")
                        .WithMany("TenderVehicleDetail")
                        .HasForeignKey("TenderVehicleSalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarDetailInfo");

                    b.Navigation("TenderVehicleSales");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.TenderVehicleSales", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.AdvertInfo", "AdvertInfo")
                        .WithMany("TenderVehicleSales")
                        .HasForeignKey("AdvertInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.Statu", "Statu")
                        .WithMany("TenderVehicleSales")
                        .HasForeignKey("StatuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvertInfo");

                    b.Navigation("Statu");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.VehicleStatuHistory", b =>
                {
                    b.HasOne("VehicleTender.API.Entity.Entities.CarDetailInfo", "CarDetailInfo")
                        .WithMany("VehicleStatuHistory")
                        .HasForeignKey("CarDetailInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTender.API.Entity.Entities.Statu", "Statu")
                        .WithMany("VehicleStatuHistory")
                        .HasForeignKey("StatuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarDetailInfo");

                    b.Navigation("Statu");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.AdvertInfo", b =>
                {
                    b.Navigation("CarDetailInfo");

                    b.Navigation("Favorite");

                    b.Navigation("Picture");

                    b.Navigation("TenderVehicleSales");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Car", b =>
                {
                    b.Navigation("CarDetailInfo");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.CarDetailInfo", b =>
                {
                    b.Navigation("IndividualVehicleSales");

                    b.Navigation("PurchasedVehicle");

                    b.Navigation("Stock");

                    b.Navigation("TenderVehicleDetail");

                    b.Navigation("VehicleStatuHistory");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Commission", b =>
                {
                    b.Navigation("CarDetailInfo");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.EnumCompanyType", b =>
                {
                    b.Navigation("CorporateDetail");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.EnumPacket", b =>
                {
                    b.Navigation("CorporateDetail");

                    b.Navigation("PacketAuthority");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.EnumStatuType", b =>
                {
                    b.Navigation("Statu");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.IndividualVehicleSales", b =>
                {
                    b.Navigation("IndividualVehiclePurchase");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.LogProcess", b =>
                {
                    b.Navigation("Log");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Notary", b =>
                {
                    b.Navigation("CarDetailInfo");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Role", b =>
                {
                    b.Navigation("RoleAuthority");

                    b.Navigation("RoleUser");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.Statu", b =>
                {
                    b.Navigation("TenderVehicleSales");

                    b.Navigation("VehicleStatuHistory");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.TenderVehicleSales", b =>
                {
                    b.Navigation("BuyingTenderVehicle");

                    b.Navigation("TenderVehicleDetail");
                });

            modelBuilder.Entity("VehicleTender.API.Entity.Entities.User", b =>
                {
                    b.Navigation("BuyingTenderVehicle");

                    b.Navigation("CarDetailInfo");

                    b.Navigation("CorporateDetail");

                    b.Navigation("Favorite");

                    b.Navigation("IndividualVehiclePurchase");

                    b.Navigation("IndividualVehicleSales");

                    b.Navigation("Log");

                    b.Navigation("Message");

                    b.Navigation("RoleUser");

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
